[package]
name = "sipua"
version = "0.0.3"
authors = ["Anatolii Kurotych <akurotych@gmail.com>"]
license = "MIT"
description = "SIP User-Agent library(FROZEN)"
edition = "2018"

[dependencies]
sipcore = { version = "0.0.1"}
